packages:
  - packages/*

allowBuilds:
  esbuild: true
  vue-demi: true

catalog:
  "@types/node": "^24.13.6"
  "@vitejs/plugin-vue": "^6.0.9"
  "@vue/tsconfig": "^0.9.1"
  "typescript": "~6.0.3"
  "vite": "^8.3.1"
  "vue-tsc": "^3.3.11"
  "vue": "^3.5.43"
  tailwindcss: ^4.3.3
  "@tailwindcss/vite": ^4.3.3

minimumReleaseAgeExclude:
  - vite@8.3.1
  - '@lucide/vue@1.50.0'
