export type { Props as TabsContentProps } from "./TabsContent.vue";
export { default as TabsContent } from "./TabsContent.vue";
export { default as TabsIndicator } from "./TabsIndicator.vue";
export { default as TabsList } from "./TabsList.vue";
export type { Props as TabsRootProps } from "./TabsRoot.vue";
export { default as TabsRoot } from "./TabsRoot.vue";
export type { Props as TabsTriggerProps } from "./TabsTrigger.vue";
export { default as TabsTrigger } from "./TabsTrigger.vue";
export type { Props as TabsTriggerNumberProps } from "./TabsTriggerNumber.vue";
export { default as TabsTriggerNumber } from "./TabsTriggerNumber.vue";
